"""
mkwall.py - Generates the built-in 792x272 1-bit wallpaper of the ELECTGPL EPD
Writer (dotted scope graticule + Smith chart) as wallpaper_builtin.h.
Run it from Thonny or any Python 3 interpreter with Pillow; edit the block below.
"""

# ---------------- CONFIGURATION (edit here) ----------------
OUTPUT_HEADER  = "wallpaper_builtin.h"
OUTPUT_PREVIEW = "wallpaper_builtin.png"
SMITH_CENTER   = (596, 150)     # pixels
SMITH_RADIUS   = 112            # pixels
# -----------------------------------------------------------

import math
from PIL import Image, ImageDraw

W, H = 792, 272


def main():
    im = Image.new("1", (W, H), 1)
    d = ImageDraw.Draw(im)
    # dotted graticule
    for y in range(28, H, 24):
        for x in range(12, W, 6):
            d.point((x, y), 0)
    for x in range(12, W, 48):
        for y in range(28, H, 6):
            d.point((x, y), 0)
    cx, cy = SMITH_CENTER
    R = SMITH_RADIUS

    def circ(x0, y0, r, clip=True):
        n = int(2 * math.pi * r * 1.5) + 60
        for i in range(n):
            a = 2 * math.pi * i / n
            x, y = x0 + r * math.cos(a), y0 + r * math.sin(a)
            if (not clip) or (x - cx) ** 2 + (y - cy) ** 2 <= R * R + 1:
                d.point((round(x), round(y)), 0)

    d.ellipse([cx - R - 6, cy - R - 6, cx + R + 6, cy + R + 6], fill=1)
    circ(cx, cy, R, False)
    circ(cx, cy, R + 1, False)
    for rn in (0.2, 0.5, 1, 2, 5):            # constant-resistance circles
        r = R / (1 + rn)
        circ(cx + R - r, cy, r)
    for xn in (0.2, 0.5, 1, 2, 5):            # constant-reactance arcs
        r = R / xn
        circ(cx + R, cy - r, r)
        circ(cx + R, cy + r, r)
    d.line([cx - R, cy, cx + R, cy], fill=0)
    circ(cx, cy, R * 0.33)                    # VSWR circle
    mx, my = cx + R * 0.33 * math.cos(-0.9), cy + R * 0.33 * math.sin(-0.9)
    d.ellipse([mx - 4, my - 4, mx + 4, my + 4], fill=0)
    d.ellipse([cx - 3, cy - 3, cx + 3, cy + 3], outline=0)
    im.save(OUTPUT_PREVIEW)

    data = bytearray()
    p = im.load()
    for y in range(H):
        for xb in range(W // 8):
            b = 0
            for k in range(8):
                if p[xb * 8 + k, y] == 0:
                    b |= 0x80 >> k
            data.append(b)
    with open(OUTPUT_HEADER, "w") as f:
        f.write("/* Built-in 792x272 wallpaper (Smith chart + scope graticule), generated by\n"
                " * tools/mkwall.py. Row-major, 99 bytes per row, MSB = leftmost, 1 = black. */\n"
                "#pragma once\n#include <stdint.h>\n")
        f.write(f"static const uint8_t wallpaper_builtin[{len(data)}] = {{\n")
        for i in range(0, len(data), 24):
            f.write("  " + ",".join("0x%02X" % v for v in data[i:i + 24]) + ",\n")
        f.write("};\n")
    print("written", OUTPUT_HEADER, len(data), "bytes")


if __name__ == "__main__":
    main()
